"""New Migration

Revision ID: 170bc148958b
Revises: d2ac150851bf
Create Date: 2023-07-03 12:35:42.496589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170bc148958b'
down_revision = 'd2ac150851bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
